version: "3.7"
services:
  back:
    build:
      context: "./back"
      dockerfile: Dockerfile
    container_name: "manos-back"
    ports:
      - "8082:8082"

  front:
    build:
      context: "./site"
      dockerfile: Dockerfile
    container_name: "manos-front"
    ports:
      - "3000:3000"
    depends_on:
      - back
